package com.ekycrail.enums;

public enum ResultCode {
    SUCCEEDED,
    NO_MATCH,
    UPSTREAM_TIMEOUT,
    UPSTREAM_UNAVAILABLE,
    PROVIDER_ERROR,
    RATE_LIMITED_UPSTREAM,
    CONSENT_NOT_FOUND,
    CONSENT_EXPIRED,
    CONSENT_REVOKED,
    CONSENT_SCOPE_MISMATCH,
    SIGNING_FAILED,
    AUDIT_WRITE_UNAVAILABLE
}
